# Basic
title: Florent's Blog
subtitle: A blog for memorizing my experience of study
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Work hard to be the best!
# creator: <a href="http://onev.cat">@onevcat</a>

url: "http://bearfighting.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: CV, description: My Projects, url: 'https://bearfighting.github.io/resume_2_english/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: bearfighting
    # duoshuo: 
    
# Social
social:
    weibo: bearfighting
    github: bearfighting
    twitter: FlorentXing
#    linkedin: in/xing-wenfeng-87a24290
    gplus: 112201708712688479753
    mail: florentxingwenfeng@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
